package dev.javis.javigg.service;

import java.util.List;

public interface IMatchDto {
    record MatchDto(MetaDataDto metadata, InfoDto info) { }
    record MetaDataDto(String dataVersion, String matchId, List<String> participants) { }
    record InfoDto(String endOfGameResult, long gameDuration, long gameEndTimestamp, long gameStartTimestamp, 
                    String gameMode, int mapId, int queueId, String gameVersion, 
                    List<ParticipantDto> participants) { }
    record ParticipantDto(int assists,
                            int baronKills,
                            int bountyLevel,
                            int champExperience,
                            int champLevel,
                            int championId,
                            String championName,
                            int damageDealtToBuildings,
                            int damageDealtToObjectives,
                            int damageDealtToTurrets,
                            int damageSelfMitigated,
                            int deaths,
                            int detectorWardsPlaced,
                            int doubleKills,
                            int dragonKills,
                            int goldEarned,
                            int goldSpent,
                            int inhibitorKills,
                            int inhibitorTakedowns,
                            int item0,
                            int item1,
                            int item2,
                            int item3,
                            int item4,
                            int item5,
                            int item6,
                            int kills,
                            String lane,
                            int largestMultiKill,
                            int magicDamageDealt,
                            int magicDamageDealtToChampions,
                            int magicDamageTaken,
                            int neutralMinionsKilled,
                            int nexusKills,
                            int nexusTakedowns,
                            int pentaKills,
                            int physicalDamageDealt,
                            int physicalDamageDealtToChampions,
                            int physicalDamageTaken,
                            int profileIcon,
                            String puuid,
                            int quadraKills,
                            String riotIdGameName,
                            String riotIdTagline,
                            String role,
                            int sightWardsBoughtInGame,
                            int teamId,
                            String teamPosition,
                            int timePlayed,
                            int totalDamageDealt,
                            int totalDamageDealtToChampions,
                            int totalDamageShieldedOnTeammates,
                            int totalDamageTaken,
                            int totalHeal,
                            int totalHealsOnTeammates,
                            int totalMinionsKilled,
                            int totalTimeCCDealt,
                            int totalTimeSpentDead,
                            int totalUnitsHealed,
                            int tripleKills,
                            int trueDamageDealt,
                            int trueDamageDealtToChampions,
                            int trueDamageTaken,
                            int turretKills,
                            int turretTakedowns,
                            int visionScore,
                            int visionWardsBoughtInGame,
                            int wardsKilled,
                            int wardsPlaced,
                            boolean win,
                            String individualPosition,
                            int killingSprees,
                            String summonerName,
                            int summonerLevel
                            ) { }
}
